services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8083:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_ENABLE_SHELL=true
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-https.tls=true"
      - "traefik.http.routers.dozzle-https.entrypoints=websecure"
      - "traefik.http.routers.dozzle-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.dozzle-https.rule=Host(`dozzle.nixlab.ch`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
