services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    ports:
      - 8082:80
    volumes:
      - /opt/containers/gotify/data:/app/data
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify-https.tls=true"
      - "traefik.http.routers.gotify-https.entrypoints=websecure"
      - "traefik.http.routers.gotify-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.gotify-https.rule=Host(`gotify.nixlab.ch`)"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
