services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /opt/containers/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PUID: ${HOMEPAGE_PUID}
      PGID: ${HOMEPAGE_PGID}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-https.tls=true"
      - "traefik.http.routers.homepage-https.entrypoints=websecure"
      - "traefik.http.routers.homepage-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.homepage-https.rule=Host(`home.nixlab.ch`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
